FROM ghcr.io/astral-sh/uv:0.12.8 AS uv

FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive
ENV ARM_GNU_PATH=/usr/local
ENV ARM_GNU_LINK=https://developer.arm.com/-/media/Files/downloads/gnu/14.3.rel1/binrel/arm-gnu-toolchain-14.3.rel1-x86_64-arm-none-eabi.tar.xz
ENV ARM_GNU_NAME=arm-gnu-toolchain-14.3.rel1-x86_64-arm-none-eabi


RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y zsh build-essential git bzip2 wget cmake ninja-build \
    software-properties-common lsb-release wget gnupg && \
    wget -O /etc/apt/trusted.gpg.d/llvm.asc https://apt.llvm.org/llvm-snapshot.gpg.key && \
    . /etc/os-release && \
    add-apt-repository "deb http://apt.llvm.org/${VERSION_CODENAME}/ llvm-toolchain-${VERSION_CODENAME}-22 main" && \
    apt-get update && \
    apt-get install -y clang-format-22 shellcheck && \
    ln -s /usr/bin/clang-format-22 /usr/bin/clang-format && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    mkdir -p ${ARM_GNU_PATH}


RUN wget -c ${ARM_GNU_LINK} -O - | tar -xJ -C ${ARM_GNU_PATH}

ENV PATH="${ARM_GNU_PATH}/${ARM_GNU_NAME}/bin:${PATH}"

COPY --from=uv /uv /uvx /usr/local/bin/
RUN uv python install 3.12

ENTRYPOINT [ "/bin/bash" ]

