site_name: MRover ESW

docs_dir: ./docs

repo_url: https://github.com/umrover/mrover-esw

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Getting Started:
      - Introduction: getting-started/intro.md
      - STM32CubeIDE: getting-started/stm32cubeide/index.md
      - Starter Projects:
          - LED: getting-started/starter/led/index.md
          - Servo:
              - Part 1 - PWM: getting-started/starter/servo/part1-pwm.md
              - Part 2 - CAN: getting-started/starter/servo/part2-can.md
          - Temp-Humidity: getting-started/starter/temp-humidity/index.md
  - Projects:
      - projects/overview26.md
  - Useful Information:
      - Timers: info/timers.md
      - Communication Protocols: info/communication-protocols/index.md
      - Brushed Motors: info/brushed.md
      - Brushless Motors: info/brushless.md
      - Science: info/science.md
      - Nucleo Information: info/nucleos.md
      - STM32 Boot: info/stm32-boot.md
  - Headers:
      - hardware.hpp: headers/hardware.md

# ignoring README.md satisfies mkdocs build --strict error
exclude_docs: |
  README.md

