name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:

  generate-test-matrix:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.load.outputs.dirs }}
    steps:
      - uses: actions/checkout@v7

      - id: load
        run: |
          {
            echo "dirs<<EOF"
            cat ci.json
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

  docker-image:
    uses: ./.github/workflows/docker.yml

  style:
    needs: docker-image
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/arm-gnu:${{ needs.docker-image.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v7

      - name: sync python env
        run: uv sync --project tools --locked

      - name: run style (format and lint)
        run: uv run --project tools --no-sync ./scripts/style.sh --format --lint

  test-build:
    needs:
      - docker-image
      - generate-test-matrix
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/arm-gnu:${{ needs.docker-image.outputs.image_tag }}

    strategy:
      fail-fast: false
      matrix:
        dir: ${{ fromJSON(needs.generate-test-matrix.outputs.dirs) }}
        preset: [ Debug, Release ]

    steps:
      - name: checkout repo and submodules
        uses: actions/checkout@v7
        with:
          submodules: 'recursive'

      - name: set parallelism
        run: echo "CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)" >> $GITHUB_ENV

      - name: build ${{ matrix.dir }} (${{ matrix.preset }})
        run: ./scripts/build.sh --src ${{ matrix.dir }} --preset ${{ matrix.preset }}

